---
title: "R Notebook"
output:
---

Remove everything
```{r}
rm(list=ls()) # clear out all variables in current session 
setwd("~")
```

Set wd
```{r}
wd = "~/Dokumente/CAU/WS_22_23/Seminar/Code/RF_GDP"
# wd = ""  # enter you wd

setwd(wd)
```

Load Packages
```{r}
source("01_load_packages.R")  # load package file

install(a = FALSE) # set a to TRUE if you want to install packages in 01_load_packages.R file
load_pack() # loading all packages after installation
```
Load Data
```{r}
df_raw = read.csv("input/current.csv") # load dataframe 
varlist_df = colnames(df_raw)
# length(varlist$fred) - 248
varlist_fred = fredqd_description # description of the quartely Fred data set

print(str(df_raw))
print(head(df_raw))
```
```{r}
dim(df)

# columns with NA's
str(df[, colSums(is.na(df)) > 0])

```
Dimensions of df: 255 rows and 246 variables (excluding the date column)

How to deal with NA entries??
e.g. df[,"TLBSNNBBDIx"] - last entry missing 
-> don't want to loose rows: Replace Using Mean, Median, or Mode ??


Clean Data frame
```{r}
source("02_data_cleaning.R") # load data file
data = clean(df_raw) # list with all relevant component extracted 
```

helper:
```{r}
# see which variables of the dataframe are in the fred description
varlist_df %in% varlist_fred$fred # returns a boolean TRUE or FALSE value depending on whether the element is found or not

which(varlist_df %in% varlist_fred$fred == FALSE) # gives the indices, that are false

varlist_df[c(which(varlist_df %in% varlist_fred$fred == FALSE))]
```


AR & RW's with different windows as benchmark:
```{r}
source("03_benchmark.R") # load data file
```




